Test/p/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{0000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test/p/force-app/main/default/objects/Employee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Enter Full Address</description>
    <label>Address</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Test/force-app/main/default/classes/Accnt.cls
@restresource(urlmapping='/showAccountdetail')
global class Accnt{
@httpget
    global static  list<employee__c> getacct(){
    list<employee__c> accts;
    try{
    accts=[select name,address__c from employee__c limit 5];
    return accts;
        }
    catch(exception ex){
    system.debug('error'+ex.getmessage());
        }
        return accts;
    }
    
    @httpdelete
    global static  list<employee__c> getdeleteacct(){
    list<employee__c> accts;
    try{
    accts=[select name,address__c from employee__c limit 2];
    return accts;
        }
    catch(exception ex){
    system.debug('error'+ex.getmessage());
        }
        return accts;
    }

}