Test/p/force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test/p/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{0000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test/p/force-app/main/default/objects/Employee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Enter Full Address</description>
    <label>Address</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Test/p/force-app/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Test/p/force-app/main/default/objects/Employee__c/fields/DateOfJoining__c.field-meta.xml
<CustomField>
    <fullName>DateOfJoining__c</fullName>
    <label>DateOfJoining</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Test/p/force-app/main/default/objects/Employee__c/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>YYYY/MM/DD</description>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

Test/p/force-app/main/default/objects/Employee__c/fields/EmpFullName__c.field-meta.xml
<CustomField>
    <fullName>EmpFullName__c</fullName>
    <label>EmpFullName</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Test/p/force-app/main/default/objects/Employee__c/fields/EmpId__c.field-meta.xml
<CustomField>
    <fullName>EmpId__c</fullName>
    <label>EmpId</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Test/force-app/main/default/classes/Emplyee.cls
public class Emplyee {
    public static void method()
    {
        try{
        employee__c emp=new employee__c();
            company__C cmpy=new company__C();
     	   emp.EmpFullName__c='kn';
           emp.DOB__c=system.today()-100;
           emp.DateOfJoining__c=system.today()-2;
           emp.Company__c=cmpy.id;
           emp.Address__c='ieg';
        emp.EmpId__c='33ww';
            insert emp;
        }
        catch(exception e){
            system.debug('error'+e);
        }
        
     
        
    }
    

}